### PR TITLE
fix: udp sockets close, power on and off brightness level

### LINKED ISSUE #2: Not closing udp sockets
https://github.com/bitfocus/companion-module-tplink-kasasmartbulb/blob/71c7c9ee35d85081635a858db2fdf34b485bbef6/src/actions.js#L31

Every time `send` is called it is opening a new udp socket on a random port. But you are only closing them if you get a response. If the device does not respond will eventually lead to exhausting all the possible port numbers, and stop things from working (eg https://github.com/bitfocus/companion/issues/2108)

You need to make sure to fail the call after some timeout, and clean it up, or it might be better to create the socket once as part of init and updateConfig and reuse it? It will require more care when listening for responses, but will ensure this can never happen

### LINKED ISSUE #4: power action always makes bulb 100% brightness
To reproduce:  set the bulb to something less than 100%, then turn off the bulb with the power off or power toggle action and then turn back with the power on or power toggle options.  The bulb will be set to 100%.

### LINKED ISSUE #5: power off action always sets the brightness to 0 instead of just turning off the bulb

### LINKED ISSUE #7: parsing of variables for actions is not correct for v3

### PR DESCRIPTION
**Pull request by digitaldrummerj**
fixes: #2 
fixes: #4 
fixes: #5 
fixes: #7

@josephdadams 
@Julusian

### CODE REVIEW

**Comment by josephdadams** [comment]
Thanks!

File: src/index.js [hunk 1]
```diff
@@ -64,8 +64,8 @@ class KasaBulbInstance extends InstanceBase {
 			}
 		}
 
-		this.getInformation()
-		this.setupInterval()
+		await this.getInformation()
```
Comment (Julusian) [inline src/index.js:67]: Awaiting this here could be problematic if the device is unreachable. If this takes longer than the timeout companion sets on the call to confogUpdated, then companion could kill and restart the connection.

Comment (digitaldrummerj) [reply src/index.js:67]: if the methods are async methods, shouldn't we await them?

Comment (Julusian) [reply src/index.js:67]: the promise the methods return needs to be handled, they dont necessarily need to be awaited.
```
this.getInformation().then(async () => {
 // do something here?
}).catch((e) => {
 // handle the error here
})
```
is a different way of handling the promise. the `then` is useful (but not necessary) to do something once the promise resolves. the `catch` is the important part, otherwise the uncaught error will cause the module's process to crash and be restarted.  
Which approach to use depends on how the execution should flow in the code

but as it stands, if that `await` takes longer than 5s, companion will see the module process as unresponsive and might restart it. 

In fact, the promise returned https://github.com/bitfocus/companion-module-tplink-kasasmartbulb/blob/master/src/index.js#L45 is not being handled. Which is lucky for now to avoid the module getting stuck in a bad state.
